version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: puppeteer-core
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 99
