version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
