on: push
name: Tests
jobs:
  tests:
    runs-on: [self-hosted]
    strategy:
      matrix:
        node: ['16']
    name: Node Tests
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.node}}
    - run: npm install
    - run: npm test
      env:
        CHROME_BIN: /usr/bin/chromium
